name: codeunion
description: Codeunion test project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.3.0
  equatable: ^2.0.5
  firebase_core: ^2.15.1
  firebase_dynamic_links: ^5.3.5
  firebase_messaging: ^14.6.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  formz: ^0.6.0
  get_it: ^7.6.0
  go_router: ^11.0.0
  google_fonts: ^5.1.0
  injectable: ^2.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.0
  sheet: 
    git: 
      url: https://github.com/jamesblasco/modal_bottom_sheet.git
      path: sheet/

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
